title: Nguyen Nam Khanh | 阮南庆
logo: docs/assets/Anh Nam Khanh.jpg
description: International Business Economics Student @ FTU | Head of Specialized Dept @ Study Abroad Club | Collaborator @ SEIB
theme: jekyll-theme-minimal
